### PR TITLE
Update checkout version

### PR DESCRIPTION
**Pull request by ArqTras**

### CODE REVIEW

**Review by shigutso — APPROVED** [review]

**Review by stoffu — CHANGES_REQUESTED** [review]
Please also update the "Recommended Aeon version" column of the "Software upgrades" table.

**Review by shigutso — CHANGES_REQUESTED** [review]
update line 97 with 0.12.7.0-aeon too

**Review by shigutso — APPROVED** [review]

**Comment by stoffu** [comment]
Please squash those two commits on the change of the version number. Also, for both commits, please rephrase the commit message to something more informative, e.g.:

- README: bump tag
- README: remove duplicated libpcsclite-dev from dependency one-liner

Also, due to a Windows-specific issue fixed in #80 , we will likely have another point release, v0.12.8.0. If this becomes the case, please update the patch accordingly.

**Comment by stoffu** [comment]
#82

**Pull request closed without merging**
