### PR TITLE
build-windows: include 5 needed DLLs in the package

### PR DESCRIPTION
**Pull request by stoffu**

### CODE REVIEW

**Comment by stoffu** [comment]
@aeonix 
This fixes #274.
Please create another release `v0.14.2.2-aeon` after merging this PR.

**Comment by aeonix** [comment]
Why is the macOS CI failing?

**Comment by iamsmooth** [comment]
Why is the macOS CI failing?

**Comment by stoffu** [comment]
It's getting a segmentation fault when finishing the IBD test mode. It used to work fine previously, and I have no idea why. Should this be fixed before releasing?

**Comment by iamsmooth** [comment]
Maybe try to assess why it is happening then decide?

**Comment by stoffu** [comment]
While I was investigating, the error disappeared somehow without me making any changes to the code. Very weird, but I guess that’s how it is with GitHub CI.

**Comment by BigslimVdub** [comment]
So are unit tests the only update for .2?

**Comment by iamsmooth** [comment]
@BigslimVdub The important update is including the DLLs so the windows build will actually work. The unit tests failed for some unknown reason and then started working again for some unknown reason.

**Pull request merged**
