### PR TITLE
Upstream merge 4

### PR DESCRIPTION
**Pull request by camthegeek**
Following @stoffu's last PR format.

This pull request merges upstream patches after [monero-project#4129](https://github.com/monero-project/monero/pull/4129) which is the last one included in #90. This PR includes upstream PRs from [monero-project#3528](https://github.com/monero-project/monero/pull/3528) merged on August 15 up to [monero-project#4223](https://github.com/monero-project/monero/pull/4223) merged on August 23:

* monero-project#3528
* monero-project#4020
* monero-project#4024
* monero-project#4089
* monero-project#4090
* monero-project#4090
* monero-project#4103
* monero-project#4106
* monero-project#4136
* monero-project#4137
* monero-project#4137
* monero-project#4138
* monero-project#4138
* monero-project#4148
* monero-project#4150
* monero-project#4153
* monero-project#4158
* monero-project#4161
* monero-project#4164
* monero-project#4165
* monero-project#4166
* monero-project#4170
* monero-project#4171
* monero-project#4172
* monero-project#4173
* monero-project#4174
* monero-project#4177
* monero-project#4186
* monero-project#4188
* monero-project#4192
* monero-project#4193
* monero-project#4194
* monero-project#4195
* monero-project#4196
* monero-project#4191
* monero-project#4131
* monero-project#4131
* monero-project#4131
* monero-project#4131
* monero-project#4179
* monero-project#4200
* monero-project#4202
* monero-project#4204
* monero-project#4207
* monero-project#4210
* monero-project#4224
* monero-project#4225
* monero-project#4231
* monero-project#4240
* monero-project#4242
* monero-project#4247
* monero-project#4249
* monero-project#3999
* monero-project#4223

Additionally, monero-project#4274 was added to fix a compile issue on Ubuntu 18.10. 

Notable updates:
**Wallet RPC** new commands
* [refresh](https://www.getmonero.org/resources/developer-guides/wallet-rpc.html#refresh)
* [get_address_index](https://www.getmonero.org/resources/developer-guides/wallet-rpc.html#get_address_index)

**Wallet CLI**
* 4188 allows users to import tx secret keys after restoring a wallet that was originally created using 3rd party wallet services such as web wallets so that tx proofs can then be generated.

This group of upstream merges contains many fixes that get us ready for the next patch that will contain many more major updates to AEON.

### CODE REVIEW

**Comment by shigutso** [comment]
Will test this ASAP, thanks for your hard work, cam!

**Comment by BigslimVdub** [comment]
Nice work Cam. I will have a chance to build on OSX high Sierra and windoze 10 hopefully tonight or tomorrow when I get my build environment set up on my new machine.

**Comment by 420coupe** [comment]
Built on Ubuntu 18.10
had to remove ustat.h from util.cpp to get it to build.

Built and tested wallet/daemon commands on testnet.

No issues.

**Comment by stoffu** [comment]
- Please rebase the branch to the current tip 01e5cde

- https://github.com/monero-project/monero/pull/4274 was already merged in #53. You reintroduced the problem when merging https://github.com/monero-project/monero/pull/4136 where <ustat.h> in addition to <sys/resource.h> got included. Please carefully read and understand the diff in the original PR and make sure not to introduce new problems.

**Comment by BigslimVdub** [comment]
Build success on native Mac OS 10.13.6. 
Version: Aeon 'Sophia' (v0.12.8.0-master-7c1d244f) ``I should probably add this to tester sheet to verify build hash is correct for PR``
Brew installed all dependencies.
Testing:
wallet-cli: opens wallet, syncs properly, transaction send and receive ok, all tested functions of CLI commands work
Daemon functions properly after sync, all tested function in daemon commands work

Issues: 
`` Daemon will not start syncing if blockchain file not in the standard location``
Using --data-dir=`location of DB` I was able to achieve a full function of daemon after DB reorg. 

## Edit
Testing on windows 10
Build success on Windows 10 18.09
version:  Aeon 'Sophia' (v0.12.8.0-master-7c1d244f)
Msys2 64bit
Testing: 
wallet-cli: opens wallet, syncs properly, transaction send and receive ok, all tested functions of CLI commands work
Daemon functions properly after sync, all tested function in daemon commands work

No issues observed during testing. Daemon functions properly.

**Comment by camthegeek** [comment]
Closing in favor of #100 -- rebased and removed duplicate merge.

**Comment by stoffu** [comment]
Opening multiple PRs on the same subject without good reason is not helpful in general. You could have just made whatever changes to your existing branch (e.g. git reset or git rebase) and force pushed the updated branch (git push -f).

**Pull request closed without merging**
