### PR TITLE
Patch 3

### PR DESCRIPTION
**Pull request by ghost**
Sorry don't know how to copy commits but this is necessary to build 
https://github.com/monero-project/monero/commit/ac0a229739c290f593059b9cba23689c94cdec94

### CODE REVIEW

**Review by stoffu — APPROVED** [review]
Next time please mention the PR number in the commit message (`/monero#NNNN` as per https://github.com/aeonix/aeon/blob/master/CONTRIBUTING.md#merging-upstream-patches) for the sake of better searchability in the log. Also very appreciated if you could learn more about how to use git, especially `git cherry-pick` and `git rebase`.

**Comment by stoffu** [comment]
https://github.com/monero-project/monero/pull/5820

**Comment by BigslimVdub** [comment]
Thanks @hsyia , should help android builds now

**Comment by ghost** [comment]
@stoffu, I will take a look at those docs and keep thta in mind for the future. I am such a noob! 

Yeah, @BigslimVdub  also check out my pull request on your build post. There are some small changes that could save future compilers some googling. https://github.com/BigslimVdub/AeonAndroidArmV8/pull/2

**Pull request merged**
