### PR TITLE
Changes to main page README.MD to apply to AEON

### PR DESCRIPTION
**Pull request by BigslimVdub**
Made changes to the rebase version of README.MD to apply to AEON. File was originally written from MONERO git readme file and did not apply to Aeon. 
Also added in appropriate compile instructions for OSX due to sammy007 not having Home-brew updated to aeon-rebase code. Instructions are still added for compiling with brew with comment for non functionality until BREW repo is updated.

### CODE REVIEW

**Comment by iamsmooth** [comment]
@BigslimVdub 

You replaced the Monero copyright notice with an AEON one. That's a big misleading. Better to leave the Monero one in place and _add_ an AEON notice. An alternate way to handle this is to move ALL of the copyright and license notices (including both AEON and Monero) to the bottom in a legal/licenses section. They don't really need to be at the very top of a readme file, as they don't convey immediately useful information when installing the software.

The cryptonote copyright notice date does not need to be updated unless we are merging new contributions from them, which as far as I know we are not.

**Comment by iamsmooth** [comment]
For the current release I'm going to leave things as they are but we can make improvements later.

**Comment by BigslimVdub** [comment]
Are you leaving the original aeonix readme or merging the monero readme with the original. We don’t want the monero related text on aeon’s git page. Also there were some updated compile instructions and other informative points taken from the aeon homepage that are useful. Feel free to edit as needed.

**Comment by stoffu** [comment]
The build instructions are exactly the same as Monero's and don't need to be changed. Your proposed changes include some wrong information such as the option to build Windows binaries using Visual Studio which is not possible in reality.

**Comment by stoffu** [comment]
> We don’t want the monero related text on aeon’s git page. 

That's just your opinion which I disagree. It's a fact that Aeon is a copy of Monero with a few critical small changes such as CryptoNight-Lite and 4min block time and zero-mixin txes. Blockchain pruning is being worked on in Monero and will likely be brought to Aeon eventually. Monero also aims at egalitarian mining and being able to run on mobile phones, albeit perhaps to a lesser degree than Aeon. In short, Monero and Aeon are just two slightly different approaches toward the ultimate goal of true digital cash, they aren't rivals.

Like with the codebase, I'd also like to keep the changes to README minimal.

**Comment by BigslimVdub** [comment]
MSVC instructions are from the main aeon page : https://github.com/aeonix/aeon/blob/master/README.md

Also it does not make sense to have under aeon git, all text referring to Monero as in irc, Reddit, monero main page. Same issue was from original rebase version where all Monero text needed to be changed to aeon because this is the Aeon build, unless that is, this project is not meant to have the Aeon name on it.

**Comment by stoffu** [comment]
> MSVC instructions are from the main aeon page : 

That information is obsolete and no longer applies now.

> Also it does not make sense to have under aeon git, all text referring to Monero as in irc, Reddit, monero main page. Same issue was from original rebase version where all Monero text needed to be changed to aeon

Of course those links need to be replaced, and other places referring to Monero need to be changed to refer to Aeon, just like I replaced user-visible strings in this patch: https://github.com/aeonix/aeon-rebase/commit/f950eb674f2c37de6d21b28aac08a54cb0e06753

This still means sparse and minimal changes, not a full rewrite or something.

**Comment by aeonix** [comment]
I agree with minimal changes to minimize confusion (such as not referring to Monero by name/links/etc. directly unless crediting it as an upstream project). There is not a need for a full rewrite, nor does most of the old AEON readme need to be retained if any of it does.

**Comment by iamsmooth** [comment]
I agree with minimal changes to minimize confusion (such as not referring to Monero by name/links/etc. directly unless crediting it as an upstream project). There is not a need for a full rewrite, nor does most of the old AEON readme need to be retained if any of it does.

**Comment by stoffu** [comment]
Almost all lines have been changed, while quite a lot of contents seem to be the same as Monero. Please refrain from random reshuffling and try to minimize changes.

**Comment by BigslimVdub** [comment]
Closing in favor of pr https://github.com/aeonix/aeon/pull/25 

Further Discussion from community on reddit post [here](https://www.reddit.com/r/Aeon/comments/8opcxa/aeon_readme_update_im_going_in_circles/)

**Pull request closed without merging**
