### PR TITLE
Fix cryptonote_tx_utils.cpp build /monero#4476

### PR DESCRIPTION
**Pull request by DeadManWalkingTO**
Fix cryptonote_tx_utils.cpp build:
Building CXX object src/cryptonote_core/CMakeFiles/obj_cryptonote_core.dir/cryptonote_tx_utils.cpp.o
In function ‘bool cryptonote::construct_miner_tx(size_t, size_t, uint64_t, size_t, uint64_t, const cryptonote::account_public_address&, cryptonote::transaction&, const blobdata&, size_t, uint8_t)’:
cc1plus: error: ‘void* __builtin_memset(void*, int, long unsigned int)’: specified size 18446744073709551608 exceeds maximum object size 9223372036854775807 [-Werror=stringop-overflow=]
cc1plus: all warnings being treated as errors
src/cryptonote_core/CMakeFiles/obj_cryptonote_core.dir/build.make:134: recipe for target 'src/cryptonote_core/CMakeFiles/obj_cryptonote_core.dir/cryptonote_tx_utils.cpp.o' failed
make[2]: *** [src/cryptonote_core/CMakeFiles/obj_cryptonote_core.dir/cryptonote_tx_utils.cpp.o] Error 1
CMakeFiles/Makefile2:1312: recipe for target 'src/cryptonote_core/CMakeFiles/obj_cryptonote_core.dir/all' failed
make[1]: *** [src/cryptonote_core/CMakeFiles/obj_cryptonote_core.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

### CODE REVIEW

**Comment by stoffu** [comment]
Hmm, this `-Werror=stringop-overflow` flag seems to be newly introduced in GCC 8. But I don't see this error when I use GCC 8.2 on Manjaro 17.1.10. What's your compiler and operating system?

Also, I don't understand why this vector resize can cause this warning/error; the compiler shouldn't be able to know the size of `out_amounts`. Do you know why/how the issue is fixed by this patch?

**Comment by DeadManWalkingTO** [comment]
OS: Ubuntu 18.04
GCC: 7.3.0

**Comment by DeadManWalkingTO** [comment]
The same issue monero-project/monero#4473 **Cannot  compile release v0.12 on Ubuntu 18 (GCC 7)**
and fix monero-project/monero#4476.

False positive 'stringop-overflow' warning.

**Comment by stoffu** [comment]
Ah, I was unaware of that PR. In this case, could you please cherry-pick the Monero commit (so that it gets the appropriate attribution) and also indicate that it's from that PR in the commit message? I usually do so by adding `/monero#NNNN` to the end of the first line of the commit message; here's an example: https://github.com/aeonix/aeon/pull/53

(BTW, it's not quite standard practice to include the full error log in the commit message.)

**Comment by DeadManWalkingTO** [comment]
Done!

**Review by stoffu — APPROVED** [review]
Thank you

**Pull request merged**
