### PR TITLE
blockchain: enforce 10 block age for spending outputs /monero#5882

### PR DESCRIPTION
**Pull request by stoffu**
Some custom wallet code apparently ignores this, which causes users
of that code to be fingerprinted

### CODE REVIEW

**Comment by stoffu** [comment]
~~Wait till the upstream PR gets merged~~

I don't think this needs further waiting as the upstream PR (which I reviewed and approved) seems to remain open only because of the maintainers' limited availability for merging PRs.

**Comment by Marzilla** [comment]
Great work... k.i.u.

**Comment by BigslimVdub** [comment]
What wallet code are you referring to?

**Comment by Marzilla** [comment]
hi and ya I sorta have very lil to say mostly but i don want to be this way... all ways . I really dint feel like the acronym was a fair way to exchange myself either, just not me tho like I said first, I am not very social and very out of touch mostly and I wish I wasnt.
is that sad ?

On Thu, Sep 5, 2019 at 9:23 PM Marsden <notifications@github.com<mailto:notifications@github.com>> wrote:
Great work... k.i.u.

**Pull request merged**
