### PR TITLE
Libversion error

### PR DESCRIPTION
**Pull request by ghost**
#204

### CODE REVIEW

**Comment by ghost** [comment]
This fixes the mac os build errors

**Comment by BigslimVdub** [comment]
Can you squash your commits and recommit? looks ok elsewise

**Comment by ghost** [comment]
Thanks, Bigslim. What is the reference to squashing commits, I haven't heard that before.

**Comment by ghost** [comment]
Is squashing comments going to remove authors? Stoffu said to use cherry pick for other's commits.

**Comment by SomaticFanatic** [comment]
No squashing commits doesn’t remove authors. Google “how do I squash commits”.

**Comment by ghost** [comment]
Oh I thought this was just big slim lingo.

**Comment by ghost** [comment]
image

**Comment by iamsmooth** [comment]
Is this ready for merge?

**Comment by BigslimVdub** [comment]
Looks like it builds on OS X fine

**Pull request merged**
