### PR TITLE
Add hard fork to cn-turtle

### PR DESCRIPTION
**Pull request by zpalmtree**
Hello,

Some of our users were interested in continuing merged mining with Aeon + TurtleCoin after our fork to cn-turtle. I thought I'd make a PR so if you guys are interested in that we can continue this cooperation.

I'm not so familiar with the Aeon codebase, so I may have missed some steps. Please let me know if I've missed something and I'll be happy to rectify it. I had to apply a patch from upstream Monero to get the code to build on my system, hope that's OK.

Currently the fork height is set to 1077777, which is in approximately 10 weeks, on April 17th.

I chose 1000000000 as the difficulty reset, as we saw TurtleCoin's difficulty reduce by roughly 4x after forking, and the current aeon diff is around 6-7000000000 - makes sense to estimate low to avoid delays.

I'm currently syncing a daemon to verify I haven't broken anything. Wallet encryption (i.e. cnv0) is working as expected between the release binaries and my fork.

I'm not sure how you prefer to testnet things, from a fork of the main chain, or a fresh chain?
Either way, there are a number of miners and pools which support cn-turtle, so setting up a testnet shouldn't be too tricky.

Thanks,

Your friends at TurtleCoin.

### Update

A full sync from zero worked fine.

### CODE REVIEW

**Comment by BigslimVdub** [comment]
Thank you for the PR. 

Would you mind educating Aeon community members as to what CN-turtle is and why it would be beneficial other then the usual algo change that pushes non cpu/gpu hardware off the network for a limited time? 
Also
Can you please explain what the benefit of merge mining is for both Aeon and Turtlecoin for this change?
Thank you for your time on this.

**Review by brandonlehmann — APPROVED** [review]

**Review by RocksteadyTC — APPROVED** [review]

**Review by bobbieltd — APPROVED** [review]

**Comment by sci-comp** [comment]
Aeon currently follows in the steps of Monero. I don't think anyone would mind we were able to lead Monero in development. However, we'd need more developers who are familiar with the Monero code base for this to happen.

As things are now, if you'd like to see a change in Aeon, then you must first get that change approved in the Monero community and pull the upstream changes.

The Monero community has been deeply debating possible PoW changes. Here are a few links to get you started:

* [Idea for ASIC resistance](https://github.com/monero-project/monero/issues/3545)
* [Time for a serious look at Proof of Work change](https://github.com/monero-project/research-lab/issues/12)
* [Proposal to consider an ASIC-friendly proof of work](https://github.com/monero-project/monero/issues/3387)

Please keep in mind that OSS moves slow and can be frustrating at times. Participants can also be rude, which is often discouraging (see Luke's recent request for a PoW change: https://github.com/monero-project/monero/issues/5085).

Good luck and thick skin!

**Comment by zpalmtree** [comment]
I see your point of view, however I fundamentally disagree.

Monero is a large project, with a large market cap, and a lot of developers. Whilst this means they get a lot of code written, it also means they move relatively slowly on making changes, as you point out.

As a smaller project, Aeon can easily innovate faster, and bring new changes. If you want to try out new PoW's, why not?

Currently, I don't see much motivation for developers to contribute to Aeon. They make a pull request, and are instead redirected to the Monero codebase. Well - they wanted to contribute to Aeon, not to Monero! Unless Aeon allows changes that are different from Monero, how will it be anything but Monero's little brother?

As to the benefits of cn-turtle - It has a smaller scratchpad, whilst also having the v2 tweaks, which are widely regarded as being difficult to implement in FPGA's and ASICS. Sure, it won't stop anyone forever, but that's how ASIC resistance goes - you need to fork often.

The smaller scratchpad is a boon for Aeon - with having a mobile focus, a proof of work which hashes faster, makes verifying blocks faster. I understand Aeon is currently working on getting a daemon working on mobiles, and it's quite slow. Easier to verify blocks will certainly help this.

It's interesting you mention Luke talking about Argon - TurtleCoin is currently experimenting with an Argon Proof of Work. I've modified the slow-hash routines to fit in with what TurtleCoin is currently using, so it would be very simple to drop in an Argon upgrade once it's finalized in TurtleCoin. Or perhaps - you could even implement it before us, why not?

Thanks.

**Comment by fexra** [comment]
@sci-comp sounds like a dead project.

**Comment by sci-comp** [comment]
It's not a matter of agreement or disagreement, it's just the way things are at the moment. 

Personally, I don't see how someone can be disconnected from the discussion going on in the Monero community and still feel confident enough to make major changes to a forked project.

If someone new who is familiar with the Monero code base comes along and would like to speed up the upstream PR process, they would likely be welcomed with open arms. 

Until then, an enormous thanks goes out to stoffu for his consistent progress.

**Comment by BigslimVdub** [comment]
> Thank you for the PR.
> 
> Would you mind educating Aeon community members as to what CN-turtle is and why it would be beneficial other than the usual algo change that pushes non cpu/gpu hardware off the network for a limited time?

* The current Turtle hash rate is 40% less than pre-fork net hash scratchpad adjusted after 24hours. Again, educate the community how using this algo is beneficial right now-immediately implemented with less than 5% of Aeon net hash being "unknown". 1MB scratchpad works for Aeon on android mobile devices with at least 2GB of ram, and quite efficiently on 4gb of ram. Quartering the scratch-pad may not increase the efficiency of a daemon, only a miner. 

> Also
> Can you please explain what the benefit of merge mining is for both Aeon and Turtlecoin for this change?
> Thank you for your time on this.

* Any response to this is still appreciated.

**Comment by cryptonote-social** [comment]
Benefit of merge mining is it brings more hashpower to both networks, and hence more security.  The other benefit of the cn-trtl algorithm is it is more CPU friendly than even cn-lite, which helps further decentralize (though perhaps there is a bigger risk of botnets garnering majority of hashpower).  Final benefit is it's probably less targeted by FPGAs, at least at this point in time.  Note how Aeon hashpower went UP instead of down after the trtl fork, despite Aeon losing all that merge-mined hashpower from TurtleCoin. This suggests specialized hardware being used for Turtlecoin moved over to Aeon and other cn-lite coins.

**Comment by BigslimVdub** [comment]
> Benefit of merge mining is it brings more hashpower to both networks, and hence more security.

* More hash power can be from individual small miners or individual large mining farms (or bot-nets), so it is a catch 22 for both involved currencies.

> The other benefit of the cn-trtl algorithm is it is more CPU friendly than even cn-lite, which helps further decentralize (though perhaps there is a bigger risk of botnets garnering majority of hashpower).

* My 8320e on CNLv7 went from 1100hs to 3200hs on CN-Trtl
However
* My 570 4GB on CNLv7 went from 1600hs to 6300hs on CN-Trtl

This is just one instance, but my own findings seem that CN-Trtl is actually more GPU friendly, being that is uses some CN-H implementations that have GPU friendliness.

> Final benefit is it's probably less targeted by FPGAs, at least at this point in time. Note how Aeon hashpower went UP instead of down after the trtl fork, despite Aeon losing all that merge-mined hashpower from TurtleCoin. This suggests specialized hardware being used for Turtlecoin moved over to Aeon and other cn-lite coins.

* Aeon had over 50% net hash "unknown" pre Turtle fork. After Turtlecoin fork Aeon has added 5 Mh to the total net hash and now under 5% of the hash power is unknown. This is only 36hrs from the fork time, but it does not seem like some 100Mh of "specialized" hardware is mining Aeon, which is actually in negative profit to mine currently, unlike Turtlecoin.

* CN-TurtleV2 is actually easier to Implement FPGA and Asics since it has the 256kb scratchad. Once an FPGA code is written for this (which may only require small tweaks from CNv8), there will be enormous increases in Turtlecoin net hash rates if it remains profitable to mine, mirroring Asic implementation in 2017. 

These are my own findings so I suggest that the Aeon community members do their own research and comment or involve themselves with this discussion.

**Comment by cryptonote-social** [comment]
"unknown" hashrate has little to do with FPGAs -- it just says a lot of hashpower is not using well known pools.  You seem to use this as a red herring to dodge the odd fact that Aeon hashpower went up after the turtlecoin fork which should have lost the Aeon network a significant chunk of hashpower. I never claimed anything about 100Mh being from specialized hardware, so not sure why you're throwing that number around.

Thanks for your CPU vs. GPU datapoint. I've been hearing differently from others around speedups, and seeing differently on my own hardware: my various CPUs are all more than 5x faster than before, whereas my GPUs (570, 580s, Vegas) are all under 4x.   More datapoints here: https://www.reddit.com/r/TRTL/comments/am53ew/post_your_hashrate_on_the_new_cn_turtle_algo/

And yes, any CN-based algorithm is targetable by FPGAs.  Fork now and fork often.

_--[Editted to add datapoints on CPU vs GPU]--_

**Comment by brandonlehmann** [comment]
> > Thank you for the PR.
> > Would you mind educating Aeon community members as to what CN-turtle is and why it would be beneficial other than the usual algo change that pushes non cpu/gpu hardware off the network for a limited time?
> 
> * The current Turtle hash rate is 40% less than pre-fork net hash scratchpad adjusted after 24hours. Again, educate the community how using this algo is beneficial right now-immediately implemented with less than 5% of Aeon net hash being "unknown". 1MB scratchpad works for Aeon on android mobile devices with at least 2GB of ram, and quite efficiently on 4gb of ram. Quartering the scratch-pad may not increase the efficiency of a daemon, only a miner.
> 

You may want to check your numbers again.

TurtleCoin block [1,199,999](https://explorer.turtlecoin.lol/block.html?hash=264539234fd8dddd8e09a62229dd0b82c6277708a1a93fbde424523ec46c7a32) shows a network hashrate of approximately 126.7MH/s on CN Lite v1 (same algo as Aeon)

TurtleCoin block [1,203,700](https://explorer.turtlecoin.lol/block.html?hash=94bfb0f54431e584430ac50092720bee7ee5e44b530379f120cc3eebb999ba0f) post fork shows a network hashrate of approximately 137.8MH/s

What seems to be swept under the rug here is that CN Turtle runs about 3-5x faster than CN Lite v1. If we normalize the new hashrate back to CN Lite v1, we're looking at 27.56MH/s to 45MH/s. This amounts to a 67% to 78% reduction in the actual network hashrate. Not only that, but it returns mining rewards back to the pre-explosion level that we all enjoyed before all that new hashrate came out of nowhere.

To put this in perspective, with ~22KH/s on CN Lite v1, I was able to mine about 29k TRTL every day or so leading up to the fork. Under the new algo, I'm back to mining around 110k TRTL per day. I think everyone can appreciate that the current move, which is by no means a final move, is a step in the right direction. It is definitely better than standing by and doing nothing.

Let me repeat that so everyone understands, post-fork, **I'm seeing about a 4x increase in my overall mining rewards** because the fork removed miners from the network. They could have been ASIC, FPGA, botnets, farms, who knows. The fact of the matter is that for right now, we're back to where we would expect to be considering an organic growth model. I think the Aeon mining community may agree that this is a **good** thing.

> Would you mind educating Aeon community members as to what CN-turtle is and why it would be beneficial other then the usual algo change that pushes non cpu/gpu hardware off the network for a limited time?

To sum it up (if you don't want to read the [article](https://blog.turtlecoin.lol/archives/proof-of-work-algorithm-change/)):

* Reduction of scratchpad size from 1mb to 256kb
* Reduction of iterations from 524,288 to 131,072
* Continued use of the "lite" variation (altered inner and outer AES rounds)
* Use of Variant 2 algo tweak

The reason that PoW algo changes are hotly debated is due to the fact that if you aren't embracing ASIC/FPGA technology then it will always be a cat and mouse game. There's literally no way to avoid this. The best anyone can hope to do is provide ASIC/FPGA resistance. Any move that a project makes to "push non cpu/gpu hardware off the network" will always be for a limited amount of time.

Discounting a proposed change because it will work "for a limited time" is not a valid reason to sit and do nothing. That's a poor stance to have in my opinion.

**Comment by zpalmtree** [comment]
I'd also like to point out that the current estimates from some of the bitstream devs for cnv2 hashrate is approximately 1kh/s.

With an eight times higher hashrate, given the 8 times smaller scratchpad, that would be 8kh/s.
Even if we're generous and say that the small scratchpad allows a higher hashrate, say, 4x higher, that would still only be 32kh/s, for a *$4000* device.

Meanwhile we see a ryzen 1700 achieving around 12kh/s, which can be picked up for ~$200.

**Comment by camthegeek** [comment]
I'm quite confused on why anyone thinks that variant 2 is helpful now. Look at the Monero hashrate growth. They are on variant 2 and I think it is very obvious at this point that variant 2 does not help. Forking is great and all (not) but it is no way to solve this issue. 

If you take a look at the numbers, the AEON hashrate barely rose post TRTL fork. We have hit 28Mh/s in the past (around Christmas) and we watched it fall. From the way it looks, we are seeing those same numbers again. Also, no other -lite coin has received additional hashrate in excess of 1Mh/s. 

Furthermore, AEON does not utilize the same difficulty adjustment as Turtlecoin (LWMA). Any sudden increases in hashrate are not entirely seen until difficulty adjust (or you calculate pool hashrates as seen on https://miningpoolstats.stream/aeon and https://aeonminingpool.com/#/stats/)  Keep in mind, blocks are 4 minutes and difficulty is averaged by the last 720 blocks. This means, the new hash on the network had to start at least 3 days prior to the increase. AEON's hashrate STARTED increasing Jan 31st 2019 at roughly 17:00 GMT. According to MPS (linked above), 3 public pools gained this hash on Jan 28th, 2019. This accounts for the 'sudden rise' of 5 Mh/s as mentioned in posts above. As of this writing, we have peaked at a difficulty of nearly 7B and are watching it drop. This could be the difficulty balancing out. 

Upon asking publicly in the Turtlecoin discord, I was informed the TRTL fork happened February 1st at roughly 14:00 GMT. Perhaps 5Mh/s of -lite decided to switch a few days ahead,, but the additional ~80Mh/s is still unaccounted for.

Right now, the majority of arguments regarding network hashrate increase have been invalid for the fact that after Turtlecoin forked, we have not seen an increase in hashrate. We have seen the increase happen prior to Turtlecoin forking. (Here, take a look at this https://aeonminingpool.com/charts/majpools.png?_ts=1549148966399) 

It's not that we want nothing to be done but there is no reason to do anything yet as nothing is happening. As time goes on and these miners readjust, we may see some additional hash rate. I think when that comes, we may have another solution prepared. As with any blockchain, time will tell. After all, slow and steady wins, right? ;) 

My final thoughts: variant 2 is a waste of time for AEON at this point. It would help but it would be very short lived especially when FPGAs have already cracked CNv2.

**Comment by thriftyMinnow** [comment]
From my research on this, going all the way down to 256k scratchpad is not something I would want to see.

**Comment by SgtTheDarknezz** [comment]
Can we please not do this, I think @camthegeek has summed it up very well.

**Comment by sci-comp** [comment]
Requesting that the issue be closed? More serious discussion for possible PoW algorithms is ongoing here: https://np.reddit.com/r/Monero/comments/aovypq/randomx_asic_resistant_pow_community_feedback/

**Comment by iamsmooth** [comment]
Do not see consensus for this so closing the PR for now. Feel free to discuss elsewhere and re-propose if you believe consensus can be achieved.

**Pull request closed without merging**
