### PR TITLE
wallet2: remove per-subaddress output selection mechanism

### PR DESCRIPTION
**Pull request by stoffu**
The subaddress scheme was introduced to Monero in October 2017 https://github.com/monero-project/monero/pull/2056 where RingCT was already deployed, which means one would typically receive just one rct output per subaddress when receiving money using subaddress as a temporary (e.g. when buying XMR anonymously at ShapeShift). For that scenario, it made sense not to mix outputs received by different subaddresses in order to prevent the slight risk of letting the malicious payer (e.g. ShapeShift) know links between different subaddresses by spending outputs received by different subaddresses together in the same transaction.

This strategy, however, poses a serious problem for Aeon which isn't using RingCT (i.e. each payment is split into multiple denominations), because limiting the source of outputs to be spent to those received by a particular subaddress used as a temporary means all the outputs received by the subaddress have been created in the same transaction; i.e. when spending outputs from a particular subaddress, **it becomes absolutely clear which outputs are real spends in the input rings because they all come from the same transaction**! This risk far outweighs the slight privacy benefit that the original design intends to bring.

### CODE REVIEW

**Comment by 420coupe** [comment]
OS: Ubuntu 16.04
VM Specs: 2 core 4GB RAM, 80GB SSD

Unable to build past 42%; see below.

https://paste.debian.net/1088679/

**Comment by stoffu** [comment]
@420coupe 
Thanks for reporting, fixed

**Comment by iamsmooth** [comment]
Merge conflict after merging some earlier PRs

**Comment by stoffu** [comment]
rebased

**Pull request merged**
