### PR TITLE
cmake: insert CMAKE_CURRENT_SOURCE_DIR in CMAKE_MODULE_PATH /monero#6586

### PR DESCRIPTION
**Pull request by ghost**
https://github.com/monero-project/monero/pull/6586

### CODE REVIEW

**Comment by tomato5040** [comment]
This is needed for new GUI

**Review by stoffu — COMMENTED** [review]
Please add /monero#6586 to the end of the commit message.
(The PR title doesn't matter from the perspective of Git commit log.)

**Comment by ghost** [comment]
Resolved.

**Review by stoffu — APPROVED** [review]

**Comment by ghost** [comment]
Ready to merge.

**Pull request merged**
