### PR TITLE
Aeon upstream 12

### PR DESCRIPTION
**Pull request by stoffu**
https://github.com/monero-project/monero/pull/4549
https://github.com/monero-project/monero/pull/4550
https://github.com/monero-project/monero/pull/4571
https://github.com/monero-project/monero/pull/4578
https://github.com/monero-project/monero/pull/4577
https://github.com/monero-project/monero/pull/4592
https://github.com/monero-project/monero/pull/4389
https://github.com/monero-project/monero/pull/4489
https://github.com/monero-project/monero/pull/4502
https://github.com/monero-project/monero/pull/4623
https://github.com/monero-project/monero/pull/4602
https://github.com/monero-project/monero/pull/4610
https://github.com/monero-project/monero/pull/4629
https://github.com/monero-project/monero/pull/4520
https://github.com/monero-project/monero/pull/4635
https://github.com/monero-project/monero/pull/4637
https://github.com/monero-project/monero/pull/4642
https://github.com/monero-project/monero/pull/4659
https://github.com/monero-project/monero/pull/4666
https://github.com/monero-project/monero/pull/4669
https://github.com/monero-project/monero/pull/4518
https://github.com/monero-project/monero/pull/4521
https://github.com/monero-project/monero/pull/4522
https://github.com/monero-project/monero/pull/4523
https://github.com/monero-project/monero/pull/4524

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Reviewed all commits.

**Comment by iamsmooth** [comment]
Is this sufficiently reviewed to merge? The last batch is from a week ago.

**Comment by stoffu** [comment]
Yes.

**Review by ghost — APPROVED** [review]
Changes are very minimal security patches and simple refactoring from monero contributors. No new features added only to fix some small bugs.

**Pull request merged**
