### PR TITLE
CONTRIBUTING: add general guideline for contributing to Aeon

### PR DESCRIPTION
**Pull request by stoffu**

### CODE REVIEW

**Comment by BigslimVdub** [comment]
The Only issue I think community members would see is that, unless they create a PR First on aeon, monero project would get the Noteriety of finding and fixing bugs, not Aeon community members. 

The process makes sense though

**Comment by thriftyMinnow** [comment]
Here is what I see as a vision for Aeon as its own project: 

After BP and RingCT are merged into Aeon, there is a solid base for Aeon to move forward as a true lighter-weight privacy coin, with its own community and dev effort.  It's blockchain will be considerably smaller and stay considerably smaller than xmr, which opens different possibilities.  We would need maybe 1 of the xmr devs to commit to becoming the lead on Aeon as their primary role, and have 2 or 3 new Devs come up to speed on the Aeon code base.  Then Aeon would be a valid crypto currency choice ... both as a user AND as a community member/volunteer, with a distinct focus from xmr.  This is more like the Litecoin and Bitcoin distinction.  

If that is not the vision for Aeon, then what is? 

If Aeon is required to forever stay months behind xmr, to the point where an Aeon bug can't even be fixed unless it is first reported/fixed in XMR and later merged ... then why should Aeon even have its own community?  Maybe it should instead be a sub-project under Monero, governed by the Monero community ... it could be re-branded as XMRL, for XMR-Lite or something.  Right now it is confusing for anyone new, because Aeon has its own branding, and its own project, and its own community, but the core code is not allowed to be independent from XMR.  That makes little sense to me.

**Comment by devopsralf** [comment]
Hey Thrifty, we could use a dev over at remix. You are welcome to contribute in any way you like. :)

**Comment by BigslimVdub** [comment]
> Hey Thrifty, we could use a dev over at remix. You are welcome to contribute in any way you like. :)

Glad to see you still follow your original choice, Aeon.

**Comment by RocksteadyTC** [comment]
Give us your idle, your un-merged, your hungry- we'll take some folks too, while they're up for grabs :D 

In all seriousness though, fork a new repo and begin active development. Then that way the community can review your work and either take a chance on something new happening or stick with what they've been doing in this repo. 

image


edit: and to the obvious "what about our wasted time if the community doesnt want our work?" I'd say 'leap and the net will appear'

**Comment by BigslimVdub** [comment]
Anyone can review and submit code to any open source project. Sometimes even forked projects of forked projects do not merge changes even though they announce anyone can make changes to their code.

**Comment by iamsmooth** [comment]
@stoffu 
> Since Aeon is Monero's clone

I'm not a fan of this wording as it is inaccurate

Random definition I pulled from the web:

> clone: an organism or cell, or group of organisms or cells, produced asexually from one ancestor or stock, to which they are genetically identical

AEON is not "genetically identical" (which in the context of software we might consider to mean identical source code), it is actually a modified version.

I think a better wording of this concept would be that AEON is forked from Monero and that the ongoing workload of continuing to merge upstream improvements is facilitated by avoiding unnecessary differences (which in turn implies submitting modifications to common code upstream). I also liked the comment about the larger community being a better source of peer review when possible.

@thriftyMinnow If you don't want to actually work on Monero directly but in working on AEON come across some improvement that you think has merit or find a bug that needs fixing, your can suggest/report it to the Monero community by making an enhancement or bug report issue rather than a pull request.

There is room for changes to AEON that are distinct from Monero, and it already has some, and will likely have others in the future. Justify them by laying out how they are _more_ or _uniquely_ applicable to AEON. With a good justification the burden of increased maintenance cost as discussed above can be overcome.

**Comment by stoffu** [comment]
@iamsmooth 
Thanks a lot for your feedback. I've done some rephrasing accordingly, please check.

> @thriftyMinnow If you don't want to actually work on Monero directly but in working on AEON come across some improvement that you think has merit or find a bug that needs fixing, your can suggest/report it to the Monero community by making an enhancement or bug report issue rather than a pull request.

Even if the author of a pull request refused to send a corresponding PR to Monero, I would do so on his/her behalf, and I'd recommend merging or rejecting the said PR based on the outcome of the peer reviewing process in Monero. In this sense, no one is prevented from working on Aeon and submitting a PR.

**Comment by camthegeek** [comment]
New changes look good to me. Thanks for clearing that up @stoffu

**Comment by iamsmooth** [comment]
@stoffu Changes look good. I plan to merge after keeping this open a while longer for feedback/review.

**Comment by thriftyMinnow** [comment]
Sorry i did not respond sooner to the discussion.  Had the holidays, family in town, then sickness.  Have been a little out of pocket.  I appreciate the comments and the changes, and am in agreement to where this ended up.  Thanks smooth, stoffu, and everyone else!!

**Pull request merged**
