### PR TITLE
GitHub Actions fix

### PR DESCRIPTION
**Pull request by stoffu**
monero/#5251
monero/#5318

### CODE REVIEW

**Comment by ghost** [comment]
I think this will have merge conflict? https://github.com/aeonix/aeon/commit/3a78b26a2b7b127a99a2025fde73c30f52f2399c#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721

**Review by ghost — APPROVED** [review]

**Comment by stoffu** [comment]
@yorha-0x 
> I think this will have merge conflict? 3a78b26#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721

Correct, I removed those commits. Thanks for pointing out.

**Comment by BigslimVdub** [comment]
can you squeeze in #236 since you added other mac OS fixes?

**Comment by stoffu** [comment]
@BigslimVdub 
OK, I've added 7689 and 7435, but I don't understand why 7074 has to do anything with Apple M1 builds.
7074 seems related to the hardware wallet which is not supported in Aeon.

Are you sure it's really needed?
Can you test this branch?

**Comment by iamsmooth** [comment]
Waiting to resolve above before merging

**Comment by ghost** [comment]
monero/monero-project#5251
monero/monero-project#5251
monero/monero-project#5318
monero/monero-project#6691
monero/monero-project#7984
monero/monero-project#7735
monero/monero-project#7689
monero/monero-project#7435

**Comment by stoffu** [comment]
On second thought it seems unnecessary to address the M1 Apple build issue #236 because this PR's focus is to make the GitHub Actions all green, which is already achieved. @BigslimVdub seems inactive these days for some reason, and it seems as if he's blocking this PR being merged which makes no sense.

As such, I've removed those two commits, and this PR is ready to be merged.

**Review by ghost — APPROVED** [review]

**Comment by BigslimVdub** [comment]
> On second thought it seems unnecessary to address the M1 Apple build issue #236 because this PR's focus is to make the GitHub Actions all green, which is already achieved. @BigslimVdub seems inactive these days for some reason, and it seems as if he's blocking this PR being merged which makes no sense.
> 
> As such, I've removed those two commits, and this PR is ready to be merged.



> @BigslimVdub OK, I've added 7689 and 7435, but I don't understand why 7074 has to do anything with Apple M1 builds. 7074 seems related to the hardware wallet which is not supported in Aeon.
> 
> Are you sure it's really needed? Can you test this branch?

I had to make all these changes to build on M1. Git workflow does not support M1 builds so this will have to be manually built and added to releases for any apple silicon support.

**Comment by stoffu** [comment]
@BigslimVdub 
The Apple M1 issue should be handled in another PR. I’d rather have this PR merged first.

**Review by BigslimVdub — APPROVED** [review]

**Comment by BigslimVdub** [comment]
@iamsmooth please merge when possible so other PR’s can be rechecked/rebased as needed

**Pull request merged**
