### PR TITLE
Add some methods to wallet RPC

### PR DESCRIPTION
**Pull request by stoffu**
- change_password
- close_wallet
- restore_deterministic_wallet
- generate_from_keys

Merged upstream PRs:

- https://github.com/monero-project/monero/pull/4269
- https://github.com/monero-project/monero/pull/4007
- https://github.com/monero-project/monero/pull/4306
- https://github.com/monero-project/monero/pull/4567
- https://github.com/monero-project/monero/pull/4746
- https://github.com/monero-project/monero/pull/5165

### CODE REVIEW

**Comment by BigslimVdub** [comment]
Looks good. Thanks!

**Comment by iamsmooth** [comment]
@BigslimVdub Did you test this at all?

**Comment by BigslimVdub** [comment]
I may not have time until this weekend to test. I will keep you updated.

**Comment by BigslimVdub** [comment]
restore functions ok
Functions seem working now. I need to edit the testnet address' for view only wallets as it is not taking the address but restore and import working good. you can merge when ready.

**Pull request merged**
