### PR TITLE
Upstream merge 3

### PR DESCRIPTION
**Pull request by stoffu**
This PR merges upstream patches after https://github.com/monero-project/monero/pull/4067 which is the last one included in #77; specifically, it includes upstream PRs from https://github.com/monero-project/monero/pull/4004 merged on July 3 up to https://github.com/monero-project/monero/pull/4129 merged on July 28:

- https://github.com/monero-project/monero/pull/4004
- https://github.com/monero-project/monero/pull/4005
- https://github.com/monero-project/monero/pull/4012
- https://github.com/monero-project/monero/pull/4028
- https://github.com/monero-project/monero/pull/4035
- https://github.com/monero-project/monero/pull/4041
- https://github.com/monero-project/monero/pull/4042
- https://github.com/monero-project/monero/pull/4043
- https://github.com/monero-project/monero/pull/3617
- https://github.com/monero-project/monero/pull/3854
- https://github.com/monero-project/monero/pull/3973
- https://github.com/monero-project/monero/pull/3981
- https://github.com/monero-project/monero/pull/4013
- https://github.com/monero-project/monero/pull/4021
- https://github.com/monero-project/monero/pull/4023
- https://github.com/monero-project/monero/pull/4029
- https://github.com/monero-project/monero/pull/4030
- https://github.com/monero-project/monero/pull/4032
- https://github.com/monero-project/monero/pull/4033
- https://github.com/monero-project/monero/pull/4047
- https://github.com/monero-project/monero/pull/4061
- https://github.com/monero-project/monero/pull/4062
- https://github.com/monero-project/monero/pull/4064
- https://github.com/monero-project/monero/pull/4075
- https://github.com/monero-project/monero/pull/4076
- https://github.com/monero-project/monero/pull/4081
- https://github.com/monero-project/monero/pull/4087
- https://github.com/monero-project/monero/pull/4088
- https://github.com/monero-project/monero/pull/3629
- https://github.com/monero-project/monero/pull/4097
- https://github.com/monero-project/monero/pull/4109
- https://github.com/monero-project/monero/pull/4110
- https://github.com/monero-project/monero/pull/4126
- https://github.com/monero-project/monero/pull/4129

### CODE REVIEW

**Comment by BigslimVdub** [comment]
is this ready to merge?
Its been 23 days and no issues brought up here.

**Comment by camthegeek** [comment]
Built on Ubuntu 16.04 and Windows 10 - no issues.
Basic functions tested: transfer [to and from], restore-deterministic-wallet, sync existing wallet, sweep_all.
RPC wallet functioning as expected.

**Comment by BigslimVdub** [comment]
I've built on docker for ubuntu 18.10 and it builds fully (can't test but it builds everything). Built on high sierra 10.13.6 no issues that I can see on send/receive/restore wallet. Also built on windows 10 msys-64 (no testing of wallet just daemon). 
I can't get this to build on 18.10 for ubuntu 18.10 (also can not build monero same setup).

**Comment by shigutso** [comment]
Built on the following OSes without issues and did a quick test of running the daemon and creating a wallet:
Ubuntu 16.04 x86_64 - kernel 4.4.0-141-generic
Ubuntu 18.04 x86_64 - kernel 4.15.0-43-generic
Ubuntu 18.10 x86_64 - kernel 4.18.0-13-generic

Unfortunately can't do more tests at the moment.

EDIT: wallet-rpc also working fine.

**Pull request merged**
