### PR TITLE
gamma selection for non-ringct outputs

### PR DESCRIPTION
**Pull request by stoffu**

### CODE REVIEW

**Comment by 420coupe** [comment]
OS: Ubuntu 16.04 
VM Specs: 2 core 4GB RAM, 80GB SSD

Unable to build past 42%; see below. 

https://paste.debian.net/1088670/

**Comment by stoffu** [comment]
@420coupe 
Thanks for reporting, fixed

**Comment by 420coupe** [comment]
OS: Ubuntu 16.04
VM Specs: 2 core 4GB RAM, 80GB SSD

Got it to build and tested daemon/cli. 

using 'status' in daemon results with the following error:
`2019-06-21 20:28:30.781     7fbe748a7700        ERROR   default contrib/epee/include/console_handler.h:388      Exception at [console_handler], what=boost::too_few_args: format-string referred to more arguments than were passed`

was able to send & receive, including using upper limit of rings (136).

**Comment by stoffu** [comment]
@420coupe 
Thanks for reporting, that issue exists in the current master, unrelated to this PR. Will fix it soon.

**Comment by 420coupe** [comment]
> @420coupe
> Thanks for reporting, that issue exists in the current master, unrelated to this PR. Will fix it soon.

This would say otherwise as it works in the current master.

```
status
Height: 1101187/1101187 (100.0%) on mainnet, not mining, net hash 21.04 MH/s, v7, out of date, likely forked, 8(out)+60(in) connections, uptime 0d 2h 27m 43s
version
Aeon 'Sophia' (v0.12.9.0-master-release)
```

**Comment by stoffu** [comment]
@420coupe 
> This would say otherwise as it works in the current master.

Nope, the current master should show the version string as

```
Aeon 'Sophia' (v0.12.9.0-master-de98ad6fd)
```

Your version string ending with `-release` means your root directory isn't a proper git repository (e.g. tarball extraction). See https://github.com/aeonix/aeon/blob/master/cmake/Version.cmake#L37

(Also, this PR cannot be the cause of the issue as it only touches the wallet code, whereas the issue exists in the daemon code.)

The issue was fixed in #119.

**Pull request merged**
