### PR TITLE
Change aeon.cash URL to HTTPS

### PR DESCRIPTION
**Pull request by shigutso**

### CODE REVIEW

**Review by stoffu — APPROVED** [review]

**Comment by iamsmooth** [comment]
I don't see that the https URL actually works I get this error (or one like it) with multiple browsers

aeon.cash uses an invalid security certificate. The certificate is only valid for the following names: *.github.com, github.com, *.github.io, github.io Error code: SSL_ERROR_BAD_CERT_DOMAIN

**Comment by shigutso** [comment]
@iamsmooth weird, for me it opens fine and the certificate is from Let's Encrypt...

image

**Comment by thinkpol2** [comment]
Works for me as well.

screenshot_2018-10-17_08-51-22

**Comment by camthegeek** [comment]
Issue: A records for aeon.cash point to old Github IP’s

Resolution: @iamsmooth needs to update IP’s according to https://help.github.com/articles/setting-up-an-apex-domain/#configuring-a-records-with-your-dns-provider

SSL only works when accessing via https://www.aeon.cash because www.aeon.cash CNAME=aeonix.github.io (which is automatic SSL).

Most modern browsers that are up to date will find the SSL certificate valid while others will throw an error.

**Comment by stoffu** [comment]
Included as part of this upstream merge PR: https://github.com/aeonix/aeon/pull/88/commits/4d6cfe9e87ce4e88a00be86d6c4e9f9728f6a771#diff-04c6e90faac2675aa89e2176d2eec7d8R22

**Pull request closed without merging**
